### ISSUE TITLE
Leaderboard stuck in "loading..." state

### ISSUE THREAD

**Issue by gabeboning** [dartmouth-cs98/18w-si32#246]
Two ways to recreate:

1. create a new group. You get redirected to the leaderboard, where the ranks load but the 'loading...' titles remain
2. Load a leaderboard, then go to a non-leaderboard page (homedash). browser back button to the leaderboard

**Comment by RobinJayaswal** [comment]
- [ ] create a new group. You get redirected to the leaderboard, where the ranks load but the 'loading...' titles remain
- [ ] Load a leaderboard, then go to a non-leaderboard page (homedash). browser back button to the leaderboard
