### ISSUE TITLE
Game runs, but does not halt. 

### ISSUE THREAD

**Issue by kyledotterrer** [dartmouth-cs98/18w-si32#260]
Presumably this is because the 'win' condition is never being met.

**Comment by gabeboning** [comment]
You sure it *never* halts? Should hit the max # of iterations eventually; unless that too is broken

**Comment by gabeboning** [comment]
sure enough... https://github.com/dartmouth-cs98/18w-si32/commit/68b57548a693b552c95c1776a2fe132fd3ca6ffa#diff-48c496417b17d69f293e2e9ef13a5bd9
