### ISSUE TITLE
Always setting state

### ISSUE THREAD

**Issue by larissachen13** [dartmouth-cs98/18w-si32#268]
https://github.com/dartmouth-cs98/18w-si32/blob/749b3f3a075580de11564cfca6d8b7636479a80a/web/src/app.jsx#L27

This is not really a large issue that needs to be addressed now, but maybe something you could think about possible other solutions for. Seems a little strange to continuously set state and re-render page because the main view is too large to store in state.

**Comment by gabeboning** [comment]
closed via https://github.com/dartmouth-cs98/18w-si32/pull/275/files#diff-8038db74f2749a994d8d2a59686a397eR26

`updateMain` is only called when the url changes and there is new data to be rendered at the root level, so we do want to force a render in there; using forceUpdate is just a little more proper than causing it via state
