### ISSUE TITLE
(see image) Receiving this account creation error leaves you in the "Registering..." state

### ISSUE THREAD

**Issue by kfxue1** [dartmouth-cs98/18w-si32#269]
Upon receiving the error, you can't make changes with valid user data.

You can recreate this by putting "a" as both the username and password.

<img width="479" alt="screenshot 2018-04-09 17 12 38" src="https://user-images.githubusercontent.com/35200789/38523364-3d841bfc-3c19-11e8-8a73-3bd6a5cca58e.png">

**Comment by gabeboning** [comment]
this one's interesting. after a failed registration for me on a duplicate name, i'm still able to enter a username/password and register. anything particular you did to be able to recreate?

**Comment by kfxue1** [comment]
I was just playing around with this a bit more, and maybe this is universal to other errors you might receiving while trying to log in?

I just used the same single-letter for both the username and password to create the error.

<img width="446" alt="screenshot 2018-04-09 20 56 45" src="https://user-images.githubusercontent.com/35200789/38530488-cb5e4e38-3c38-11e8-8397-f280a3fed647.png">
