### ISSUE TITLE
Commented out function

### ISSUE THREAD

**Issue by mahnoormaqsood** [dartmouth-cs98/18w-si32#270]
https://github.com/dartmouth-cs98/18w-si32/blob/29e31c4aac3279a2ed3803b6920265e2443e83ba/web/src/components/replay/Canvas.jsx#L85

What does this function do? Will you be using it in the future?

**Comment by gabeboning** [comment]
addressed in https://github.com/dartmouth-cs98/18w-si32/commit/1296e238d456d41d587afdc80c70c5e700166fde
