### ISSUE TITLE
Move command validation

### ISSUE THREAD

**Issue by mortiz18** [dartmouth-cs98/18w-si32#273]
Are move commands always considered valid, or is there a scenario in which the bot is prevented from accessing a certain unit?

https://github.com/dartmouth-cs98/18w-si32/blob/29e31c4aac3279a2ed3803b6920265e2443e83ba/worker/bot_common/GameHelper.py#L38

**Comment by gabeboning** [comment]
the game itself validates that a move made by any user is legit: i.e. that player actually has those units in that square, and the square moving to is valid. In the helper, we do not check for a user.
