### ISSUE TITLE
display "no results" in user search on dash

### ISSUE THREAD

**Issue by kyledotterrer** [dartmouth-cs98/18w-si32#405]

**Comment by gabeboning** [comment]
should already do that: 

![image](https://user-images.githubusercontent.com/1010522/40520506-7a29d044-5f94-11e8-8473-d93c87f93e96.png)

**Comment by kyledotterrer** [comment]
yea I saw that after looking at the code, but a couple of times I saw people try it today and get no feedback.

**Comment by kyledotterrer** [comment]
still going to mark this as resolved though.
