### ISSUE TITLE
Create and return a match if no matches in queue

### ISSUE THREAD

**Issue by gabeboning** [dartmouth-cs98/18w-si32#64]
When worker requests a next task and there are no queued matches, create and return a random (somewhat even?) match instead of just having the worker spin.

**Comment by RobinJayaswal** [comment]
Outline for algo determining next game: 

- [ ] Choose one player we want to play next. Who plays next? Should probably give more weight to 1) new bots 2) bots with less games (this might implicitly take care of point 1) 3) who has not played in a while
- [ ] Once we find one player, find them an opponent. Same criteria as above, but add extra constraint that their ranking is close.

Concern: This gives much more weight to the lower ranks, so we will see many more games for those bots than for the people at the top / old bots. Thats fine to some extent, but should make sure that activity is not exclusively at the bottom.
